# configure.in for frontline
#
# Author: Masatake YAMATO (jet@gyve.org)
#
AC_INIT(main.c)

#
# version setting up for Automake
#
AUTOTRACE_MAJOR_VERSION=0
AUTOTRACE_MINOR_VERSION=32
AUTOTRACE_MICRO_VERSION=0
AUTOTRACE_VERSION=${AUTOTRACE_MAJOR_VERSION}.${AUTOTRACE_MINOR_VERSION}.${AUTOTRACE_MICRO_VERSION}
AC_DEFINE_UNQUOTED(AUTOTRACE_VERSION,"$AUTOTRACE_VERSION")
AC_SUBST(AUTOTRACE_VERSION)
AM_INIT_AUTOMAKE(autotrace, $AUTOTRACE_VERSION, no-define)

#
# version setting up for libtool
#
LT_CURRENT=3
LT_REVISION=0
LT_AGE=0
dnl AC_SUBST(LT_RELEASE)
AC_SUBST(LT_CURRENT)
AC_SUBST(LT_REVISION)
AC_SUBST(LT_AGE)
dnl AC_SUBST(LT_CURRENT_MINUS_AGE)
AC_PROG_CC
AC_PROG_LIBTOOL

AUTOTRACE_WEB=https://github.com/pjobson/AutoTrace
AC_DEFINE_UNQUOTED(AUTOTRACE_WEB, "$AUTOTRACE_WEB")

AM_MAINTAINER_MODE

AM_CONFIG_HEADER(config.h)

AC_PROG_CPP
AC_PROG_RANLIB
dnl AC_CANONICAL_HOST
dnl AC_ARG_PROGRAM
AM_SANITY_CHECK
AC_PROG_INSTALL
AC_CHECK_HEADERS(malloc.h)

dnl
dnl ImageMagick
dnl
HAVE_MAGICK=no
AC_ARG_WITH(magick,
[  --with-magick  compile with ImageMagick (default)
  --without-magick  compile without ImageMagick],,with_magick=yes)

if test $with_magick = yes ; then
	dnl Check for pkg-config first
	AC_PATH_PROG(PKG_CONFIG, pkg-config, no)
	if test "x$PKG_CONFIG" != "xno" ; then
		dnl Try MagickWand (ImageMagick 6+)
		if $PKG_CONFIG --exists MagickWand ; then
			AC_MSG_CHECKING([for ImageMagick 6+ via pkg-config])
			MAGICK_VERSION=`$PKG_CONFIG --modversion MagickWand`
			MAGICK_CFLAGS=`$PKG_CONFIG --cflags MagickWand`
			MAGICK_LDFLAGS=`$PKG_CONFIG --libs MagickWand`
			AC_MSG_RESULT([yes ($MAGICK_VERSION)])
			HAVE_MAGICK=yes
			AC_DEFINE(HAVE_MAGICK)
			AC_SUBST(MAGICK_CFLAGS)
			AC_SUBST(MAGICK_LDFLAGS)
		dnl Try MagickCore (ImageMagick 7+)
		elif $PKG_CONFIG --exists MagickCore ; then
			AC_MSG_CHECKING([for ImageMagick 7+ via pkg-config])
			MAGICK_VERSION=`$PKG_CONFIG --modversion MagickCore`
			MAGICK_CFLAGS=`$PKG_CONFIG --cflags MagickCore`
			MAGICK_LDFLAGS=`$PKG_CONFIG --libs MagickCore`
			AC_MSG_RESULT([yes ($MAGICK_VERSION)])
			HAVE_MAGICK=yes
			AC_DEFINE(HAVE_MAGICK)
			AC_SUBST(MAGICK_CFLAGS)
			AC_SUBST(MAGICK_LDFLAGS)
		else
			AC_MSG_WARN([*** pkg-config found but MagickWand/MagickCore not found ***])
			AC_MSG_WARN([*** ImageMagick input handler is disabled.                ***])
		fi
	fi

	dnl Fallback to *-config if pkg-config fails
	if test $HAVE_MAGICK = no ; then
		AC_CHECK_PROG(MAGICK_CONFIG, MagickWand-config, MagickWand-config, "")
		if test "x$MAGICK_CONFIG" != "x" ; then
			AC_MSG_CHECKING([for ImageMagick via MagickWand-config])
			MAGICK_VERSION=`$MAGICK_CONFIG --version`
			MAGICK_CFLAGS=`$MAGICK_CONFIG --cflags`
			MAGICK_LDFLAGS=`$MAGICK_CONFIG --ldflags`
			MAGICK_LDFLAGS="$MAGICK_LDFLAGS `$MAGICK_CONFIG --libs`"
			AC_MSG_RESULT([yes ($MAGICK_VERSION)])
			HAVE_MAGICK=yes
			AC_DEFINE(HAVE_MAGICK)
			AC_SUBST(MAGICK_CFLAGS)
			AC_SUBST(MAGICK_LDFLAGS)
		else
			AC_CHECK_PROG(MAGICK_CONFIG, MagickCore-config, MagickCore-config, "")
			if test "x$MAGICK_CONFIG" != "x" ; then
				AC_MSG_CHECKING([for ImageMagick via MagickCore-config])
				MAGICK_VERSION=`$MAGICK_CONFIG --version`
				MAGICK_CFLAGS=`$MAGICK_CONFIG --cflags`
				MAGICK_LDFLAGS=`$MAGICK_CONFIG --ldflags`
				MAGICK_LDFLAGS="$MAGICK_LDFLAGS `$MAGICK_CONFIG --libs`"
				AC_MSG_RESULT([yes ($MAGICK_VERSION)])
				HAVE_MAGICK=yes
				AC_DEFINE(HAVE_MAGICK)
				AC_SUBST(MAGICK_CFLAGS)
				AC_SUBST(MAGICK_LDFLAGS)
			else
				AC_MSG_WARN([*** ImageMagick not found.                          ***])
				AC_MSG_WARN([*** ImageMagick input handler is disabled.          ***])
			fi
		fi
	fi
fi
AM_CONDITIONAL(HAVE_MAGICK, test $HAVE_MAGICK = yes)

dnl
dnl LIBPNG
dnl

dnl Test for zlib (from gimp-1.1.29)
HAVE_ZLIB=no
AC_CHECK_LIB(z, gzsetparams,
      	     [AC_CHECK_HEADER(zlib.h,
	                     HAVE_ZLIB=yes,
	                     AC_MSG_WARN(*** ZLIB header files not found: PNG Input will be disabled. ***))],
	     AC_MSG_WARN(*** ZLIB library files not found: PNG Input will be disabled. ***))

dnl Test for libpng
HAVE_LIBPNG_STAGE1=no
AC_CHECK_LIB(png, png_get_image_width,
	HAVE_LIBPNG_STAGE1=yes ,,-lz -lm)

HAVE_LIBPNG=no
if test "x$HAVE_LIBPNG_STAGE1" = "xyes" ; then
	AC_CHECK_LIB(png, png_read_png,
		HAVE_LIBPNG=yes ,,-lz -lm)
	if test "x$HAVE_LIBPNG" = "xyes" ; then
		LIBPNG_LDFLAGS="-lpng -lz -lm"
		AC_SUBST(LIBPNG_LDFLAGS)
		AC_DEFINE(HAVE_LIBPNG)
	else
	   AC_MSG_WARN([*** libpng exists but cannot find png_read_png in the libpng. ***])
	   AC_MSG_WARN([*** libpng might be old.                                      ***])
	   AC_MSG_WARN([*** You need libpng 1.0.6 or higher.                          ***])
	   AC_MSG_WARN([*** Png input handler is disabled.                            ***])
	fi
else
	AC_MSG_WARN([*** Cannot find libpng.            ***])
	AC_MSG_WARN([*** Png input handler is disabled. ***])
fi
AM_CONDITIONAL(HAVE_LIBPNG, test $HAVE_LIBPNG = yes)


dnl
dnl Suppressing linker warning
dnl 
dnl On MacOS X(Darwin), getopt related symbols are defined 
dnl in /usr/lib/libm.dylib. They are conflicted with symbols 
dnl defined in getopt* of autotrace. To avoid warning-messages 
dnl about this confliction, "-multiply_defined suppress" is 
dnl passed to ld if autotrace is built on Darwin.
dnl
dnl BTW, Is getopt mathematical function?
dnl 
dnl libm.dylib on Darwin problem is reported by 
dnl Martin Kerscher <kerscher@theorie.physik.uni-muenchen.de>
dnl
AC_MSG_CHECKING([whether the host is Darwin])
case $host_os in
     darwin*) LDFLAGS="-Xlinker -multiply_defined -Xlinker suppress ${LDFLAGS}"
     AC_MSG_RESULT([yes])
     AC_MSG_WARN([linker messages that warns symbols are multiply defined 
are suppressed])
     ;;
     *)	
     AC_MSG_RESULT([no])
     ;;
esac


dnl
dnl Vender's cc(not gcc)
dnl
dnl if test "x$CC" = xcc ; then
dnl   case host in
dnl 	mips-sgi-irix*)
dnl # Peter Cucka <pcucka at anim.dreamworks.com> wrote:
dnl # > Should I use -Ofast instead of -O2?
dnl # -Ofast selects optimizations that maximize speed, at the expense of
dnl # size, compile time, and, in some cases, floating point accuracy.
dnl # Compiled with -Ofast, AutoTrace runs about twice as fast as with -O2,
dnl # or even -O3, on the two machines (admittedly not a very extensive
dnl # sample) on which I've tested it.  I'd recommend using -Ofast, but
dnl # it's not necessary.
dnl            CFLAGS=-Ofast
dnl            ;;
dnl 	*)
dnl	    ;;
dnl  esac
dnl fi

AC_OUTPUT([Makefile autotrace-config autotrace.pc autotrace.spec], 
[chmod a+x autotrace-config])

echo "

Configuration:
	imagemagick output support:	$HAVE_MAGICK
	libpng output support:		$HAVE_LIBPNG

"
